apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hpas.yaml

patches:
  - path: patches/credit-api.yaml
    target:
      kind: Deployment
      name: credit-api
  - path: patches/mlflow.yaml
    target:
      kind: Deployment
      name: mlflow
  - path: patches/llm-api.yaml
    target:
      kind: Deployment
      name: llm-api
  - path: patches/llm-langgraph-api.yaml
    target:
      kind: Deployment
      name: llm-langgraph-api
  - path: patches/llm-trino-mcp.yaml
    target:
      kind: Deployment
      name: llm-trino-mcp
  - path: patches/spark-worker.yaml
    target:
      kind: Deployment
      name: spark-worker
  - path: patches/airflow-worker.yaml
    target:
      kind: Deployment
      name: airflow-worker
  - path: patches/airflow-apiserver.yaml
    target:
      kind: Deployment
      name: airflow-apiserver
