apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
spec:
  template:
    spec:
      containers:
        - name: llm-api
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 8Gi
