apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
spec:
  template:
    spec:
      containers:
        - name: spark-worker
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              memory: 5Gi
