apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql.yaml
  - hive-metastore.yaml
  - trino.yaml
  - pgvector.yaml

configMapGenerator:
  - name: hive-metastore-config
    files:
      - ../../trino/hive-metastore/conf/core-site.xml
      - ../../trino/hive-metastore/conf/hive-site.xml
      - ../../trino/hive-metastore/conf/metastore-site.xml
    options:
      disableNameSuffixHash: true
  - name: trino-main-config
    files:
      - ../../trino/trino/etc/config.properties
      - ../../trino/trino/etc/jvm.config
      - ../../trino/trino/etc/log.properties
      - ../../trino/trino/etc/node.properties
    options:
      disableNameSuffixHash: true
  - name: trino-catalog-config
    files:
      - ../../trino/trino/etc/catalog/iceberg.properties
      - pgvector.properties
      - ../../trino/trino/etc/catalog/tpch.properties
      - ../../trino/trino/etc/catalog/tpcds.properties
    options:
      disableNameSuffixHash: true
