apiVersion: v1
kind: Service
metadata:
  name: trino
  labels:
    app: trino
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: trino
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  labels:
    app: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      initContainers:
        - name: wait-metastore
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z hive-metastore 9083; do sleep 3; done
      containers:
        - name: trino
          image: gruponddados/trino:469
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: trino-main
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-main
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-main
              mountPath: /etc/trino/log.properties
              subPath: log.properties
            - name: trino-main
              mountPath: /etc/trino/node.properties
              subPath: node.properties
            - name: trino-catalog
              mountPath: /etc/trino/catalog
          readinessProbe:
            httpGet:
              path: /v1/info
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: trino-main
          configMap:
            name: trino-main-config
        - name: trino-catalog
          configMap:
            name: trino-catalog-config
