apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

secretGenerator:
  - name: platform-secrets
    envs:
      - secrets.env
    options:
      disableNameSuffixHash: true

configMapGenerator:
  - name: platform-config
    literals:
      - POSTGRES_HOST=mlflow-postgres
      - MLFLOW_AUTH_DB=mlflow_auth
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - MLFLOW_S3_IGNORE_TLS=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_TOPIC=predict
      - KAFKA_CONSUMER_GROUP_ID=credit-risk-forecast-consumer
      - KAFKA_TOPIC_PARTITIONS=3
      - KAFKA_TOPIC_REPLICATION_FACTOR=1
      - SPARK_MASTER_URL=local[2]
      - SPARK_HIVE_METASTORE_URIS=thrift://hive-metastore:9083
      - SPARK_SQL_WAREHOUSE_DIR=s3a://lakehouse/
      - SPARK_S3A_ENDPOINT=http://minio:9000
      - LAKEHOUSE_WRITE_REPARTITION=0
      - TRINO_HOST=trino
      - TRINO_PORT=8080
      - TRINO_HTTP_SCHEME=http
      - TRINO_MCP_SSE_URL=http://llm-trino-mcp:8765/sse
      - TRINO_MCP_HOST=llm-trino-mcp
      - PGVECTOR_HOST=pgvector
      - PGVECTOR_PORT=5432
      - DOCUMENTS_DIR=/app/documents
      - RAG_AUTO_INGEST=false
      - LLM_IN_DOCKER=1
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - BASE_MODEL=Qwen/Qwen2.5-0.5B-Instruct
      - ADAPTER_REPO=Glccampos/llm_qween
      - SKIP_PREFETCH=true
    options:
      disableNameSuffixHash: true
